FROM bats/bats:v1.10.0

RUN apk --no-cache --update add \
  gettext jq git python3 py3-pip
RUN pip install yq

WORKDIR /sloctl

COPY ./test ./test
COPY --from=sloctl-unit-test-bin /usr/bin/sloctl /usr/bin/sloctl

# Required for bats pretty printing.
ENV TERM=linux
