FROM bats/bats:1.11.0

RUN apk --no-cache --update add \
  gettext jq git python3 py3-pip
RUN pip install yq

WORKDIR /sloctl

COPY ./test ./test
COPY --from=sloctl-e2e-test-bin /usr/bin/sloctl /usr/bin/sloctl

ENV SLOCTL_NO_CONFIG_FILE=true
# Required for bats pretty printing.
ENV TERM=linux
