name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: ⚠️  Breaking Changes
    labels:
      - breaking-change
  - title: 🚀 Features
    labels:
      - enhancement
  - title: 💻 Fixed Vulnerabilities
    labels:
      - security
  - title: 🐞 Bug Fixes
    labels:
      - bug
  - title: 🧰 Maintenance
    collapse-after: 3
    labels:
      - chore
      - infrastructure
      - dependencies
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
autolabeler:
  # Pull requests scope.
  - label: enhancement
    title:
      - "/^feat:/i"
  - label: chore
    title:
      - "/^chore:/i"
  - label: infrastructure
    title:
      - "/^infra:/i"
  - label: security
    title:
      - "/^sec:/i"
  - label: bug
    title:
      - "/^fix:/i"
  - label: documentation
    title:
      - "/^doc:/i"
  - label: breaking-change
    body:
      - '/^## Breaking Changes/im'
  - label: release-notes
    body:
      - '/^## Release Notes/im'
  # Version labels.
  - label: minor
    title:
      - "/^feat:/i"
  - label: patch
    title:
      - "/^fix:/i"
      - "/^sec:/i"
      - "/^chore:/i"
    branch:
      - '/^renovate_/'
  # Languages detection.
  - label: go
    files:
      - '*.go'
      - 'go.mod'
      - 'go.sum'
  - label: python
    files:
      - '*.py'
  - label: javascript
    files:
      - '*.js'
replacers:
  # Remove unlabeled or uncategorized PRs.
  - search: "/# What's Changed.*?\\n## /s"
    replace: "# What's Changed\n\n## "
template: |
  # What's Changed

  $CHANGES
