builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X github.com/nobl9/sloctl/internal/sloctl.BuildVersion={{.Version}} -X github.com/nobl9/sloctl/internal/sloctl.BuildGitBranch={{ .Env.BRANCH }} -X github.com/nobl9/sloctl/internal/sloctl.BuildGitRevision={{ .Env.REVISION }}'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
  binary: 'sloctl'
archives:
- format: binary
  name_template: 'sloctl-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Version }}'
checksum:
  name_template: sloctl-{{ .Version }}-SHA256SUMS'
  algorithm: sha256
release:
  github:
      owner: nobl9
      name: sloctl
brews:
  - name: sloctl
    tap:
      owner: nobl9
      name: homebrew-sloctl
      branch: main
    commit_msg_template: "Brew formula update for sloctl version {{ .Version }}"
    homepage: "https://nobl9.com"
    description: "Command-line client for Nobl9"
    commit_author:
      name: nobl9
      email: support@nobl9.com
    test: |
      assert_predicate bin/"sloctl", :exist?
      system "sloctl", "--help"
    install: |
      bin.install Dir['sloctl-*-{{ .Version }}'].first()  => "sloctl"
    caveats: |
      Thank you for installing the command-line client for Nobl9!

      To see help and a list of available commands type:
        $ sloctl help

      For more information on how to use the command-line client
      and the Nobl9 managed cloud service, visit:
        https://docs.nobl9.com/sloctl-user-guide
    folder: Formula
