version: "1.0"

stages:
  - "clone"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "nobl9/sloctl"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  install:
    title: "Install sloctl"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "apt-get update"
      - "apt-get install -y git"
      - "apt-get install zip unzip"
      - "unzip sloctl-linux-*.zip"
      - "rm sloctl-*.zip"
      - "cf_export VERSION=$(git describe --tags --abbrev=0)"
    stage: "build"

  build:
    title: "Building docker image"
    type: "build"
    working_directory: "${{clone}}"
    arguments:
      image_name: "nobl9/sloctl"
      dockerfile: 'Dockerfile'
      registry: "nobl9"
      tags: 
        - "latest"
        - "v${{VERSION}}"
    stage: "build"
    