Output demo.gif

Require sloctl

Set Shell "bash"
Set FontSize 28
Set Width 1200
Set Height 700

Type "sloctl config add-context" Sleep 500ms Enter
Type "new-context" Sleep 500ms Enter
Type "my-id" Sleep 500ms Enter
Type "secret" Sleep 500ms Enter
Down Sleep 200ms Down Sleep 200ms Enter
Type "https://dev-orange.nobl9.dev" Sleep 500ms Enter
Type "ausdh506kj9JJVw3g4x6" Sleep 500ms Enter
Sleep 500ms Enter
Sleep 500ms Enter

Sleep 1s
