blank_issues_enabled: false
contact_links:
  - name: Nobl9 Support
    url: https://www.nobl9.com/contact/support
    about: If you need help related to the whole Nobl9 platform or want the problem to remain private, contact us here.
