FROM bats/bats:1.14.0

# Pin bats-assert separately because the Bats image lacks assert_stderr.
ARG BATS_ASSERT_VERSION=2.2.4
RUN /tmp/docker/install_libs.sh assert "${BATS_ASSERT_VERSION}"

RUN apk --no-cache --update add \
  gettext jq git python3 py3-pip openssl tzdata npm
RUN pip install yq==v3.2.3 --break-system-packages

WORKDIR /sloctl

COPY ./test ./test
COPY ./install.bash ./install.bash
COPY --from=sloctl-unit-test-bin /usr/bin/sloctl /usr/bin/sloctl

# Required for bats pretty printing.
ENV TERM=linux
