FROM bats/bats:1.11.0

RUN apk --no-cache --update add \
  gettext jq git python3 py3-pip
# Pinned due to https://github.com/kislyuk/yq/issues/187.
RUN pip install yq==v3.2.3 --break-system-packages

WORKDIR /sloctl

COPY ./test ./test
COPY --from=sloctl-e2e-test-bin /usr/bin/sloctl /usr/bin/sloctl

ENV SLOCTL_NO_CONFIG_FILE=true
# Required for bats pretty printing.
ENV TERM=linux
