FROM bats/bats:1.11.1

RUN apk --no-cache --update add \
  gettext jq git python3 py3-pip openssl
RUN pip install yq==v3.2.3 --break-system-packages

WORKDIR /sloctl

COPY ./test ./test
COPY ./install.bash ./install.bash
COPY --from=sloctl-unit-test-bin /usr/bin/sloctl /usr/bin/sloctl

# Required for bats pretty printing.
ENV TERM=linux
