on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  merge_group:
name: pr-title
jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
    - uses: Slashgear/action-check-pr-title@v4.3.0
      with:
        regexp: "^(feat|fix|sec|infra|test|chore|doc): .{5,}"
        helpMessage: "Example: 'feat: new pr title check BE-143' <- prefix, colon, space, PR title of at least 5 chars (with ticket number strongly suggested, but not mandatory)"
