name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Release Binaries
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip=homebrew
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
