name: Release Drafter

on:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  # 'edited' event is required to account for initial invalid PR names
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  autolabeler:
    if: github.event_name == 'pull_request'
    permissions:
      # write permission is required to add labels to pull requests
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        with:
          token: ${{ secrets.RELEASE_LABELER_TOKEN }}

  update_release_draft:
    if: github.event_name == 'push'
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.drafter.outputs.tag_name }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - id: drafter
        uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.RELEASE_LABELER_TOKEN }}

  update_release_notes:
    needs: update_release_draft
    permissions:
      # write permission is required to edit the github release
      contents: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_LABELER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
      - name: Add release notes to the draft
        run: .github/scripts/release-notes.sh ${{ needs.update_release_draft.outputs.tag_name }}
