name: Release candidate
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  test:
    uses: ./.github/workflows/e2e-tests.yml
    with:
      clientId: "${{ vars.SLOCTL_CLIENT_ID }}"
      ref: "${{ github.ref_name }}"
    secrets:
      clientSecret: "${{ secrets.SLOCTL_CLIENT_SECRET }}"
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Release Binaries
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip=homebrew
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
