name: release-sloctl

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  determine-version:
    name: Decide on sloctl release version by parsing the tag name
    runs-on: ubuntu-latest
    steps:
      - name: Set VERSION using the tag
        id: get_version
        run: |
          echo ::set-output name=SLOCTL_VERSION::${GITHUB_REF##*/}
    outputs:
      sloctl-version: ${{ steps.get_version.outputs.SLOCTL_VERSION }}

  build:
    name: Create Release
    needs: determine-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          set -x
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "${{ needs.determine-version.outputs.sloctl-version }}" "${{ needs.determine-version.outputs.sloctl-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
