- slo: gandalf
  project: fangorn
  from: 2023-02-02T15:02:05Z
- slo: aragorn
  project: minas-tirith
  from: 2023-02-02T15:02:05+02:00
- slo: legolas
  project: lorien
  from: 2023-02-02T15:02:10+01:00
